# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: teamcrits
description: Enables permanent crits for either team
homepage: "https://github.com/leighmacdonald/uncletopia"
inputs:
  - teamcrits.sp
version: 1.0.0
