# yaml-language-server: $schema=../plugin.schema.json
---
name: unusedvoicelines
description: "Plays unused announcer voicelines, class speeches, & sounds/music"
homepage: "https://steamcommunity.com/id/xNanochip/"
authors:
  - Nanochip
inputs:
  - unusedvoicelines.sp
version: 1.1.0
