# yaml-language-server: $schema=https://raw.githubusercontent.com/leighmacdonald/smpkg-repo/refs/heads/master/schema.yaml

name: class_restrict
homepage: https://forums.alliedmods.net/showthread.php?p=642353
