# yaml-language-server: $schema=../plugin.schema.json
---
name: class_restrict
description: Class restrictions
homepage: "https://forums.alliedmods.net/showthread.php?p=642353"
version: 0.6.1
inputs:
  - classrestrict.sp
configs:
  - name: classrestrict.cfg
    values:
      sm_classrestrict_enabled: "1"
      sm_classrestrict_flags: ""
      sm_classrestrict_immunity: "0"
      sm_classrestrict_blu_demomen: "-1"
      sm_classrestrict_blu_engineers: "-1"
      sm_classrestrict_blu_heavies: "-1"
      sm_classrestrict_blu_medics: "-1"
      sm_classrestrict_blu_pyros: "-1"
      sm_classrestrict_blu_scouts: "-1"
      sm_classrestrict_blu_snipers: "-1"
      sm_classrestrict_blu_soldiers: "-1"
      sm_classrestrict_blu_spies: "-1"
      sm_classrestrict_red_demomen: "-1"
      sm_classrestrict_red_engineers: "-1"
      sm_classrestrict_red_heavies: "-1"
      sm_classrestrict_red_medics: "-1"
      sm_classrestrict_red_pyros: "-1"
      sm_classrestrict_red_scouts: "-1"
      sm_classrestrict_red_snipers: "-1"
      sm_classrestrict_red_soldiers: "-1"
      sm_classrestrict_red_spies: "-1"
