# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: enablewhitelist
description: >-
  Force-enables tournament mode only when loading and applying the item
  whitelist.
homepage: "https://forums.alliedmods.net/showthread.php?p=2819339"
authors:
  - Sappykun
inputs:
  - enablewhitelist.sp
version: 1.0.1
