# Schema for package.yaml
type: object
properties:
  name:
    type: string
    description: The name of the plugin
  dependencies:
    type: array
    items:
      type: string
    description: List of dependencies
  inputs:
    type: array
    items:
      type: string
    description: List of input plugin scripts (.sp) to build
  authors:
    type: array
    items:
      type: string
    description: List of authors
  version:
    type: string
    description: The version of the application
  description:
    type: string
    description: Description of the plugin
  license:
    type: string
    description: The license of the plugin
  homepage:
    type: string
    description: The homepage of the plugin

required:
  - name
