# yaml-language-server: $schema=../plugin.schema.json
---
name: halloween_cosmetic_enabler
description: Protects players with reserve slot from being autokicked
authors:
  - Mikusch
homepage: "https://github.com/Mikusch/HalloweenCosmeticEnabler"
inputs:
  - hwn_cosmetic_enabler.sp
version: 1.3.1
