$schema: >-
  https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json
name: sm_nocontracker
description: Blocks Contracker
homepage: ""
authors:
  - Malifox
  - Sreaper
inputs:
  - sm_nocontracker.sp
version: 1.1.0
