# yaml-language-server: $schema=../plugin.schema.json
---
name: sm_nocontracker
description: Blocks Contracker
homepage: ""
authors:
  - Malifox
  - Sreaper
inputs:
  - sm_nocontracker.sp
version: 1.1.0
