# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: send_to_spec
description: A simple spectator manager.
homepage: ""
inputs:
  - SendToSpec.sp
version: 1.0.0
