# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: stopwatch
description: Allows using Stopwatch mode without enabling Tournament mode.
homepage: "https://github.com/Mikusch/stopwatch"
authors:
  - Mikusch
inputs:
  - stopwatch.sp
version: 1.0.0
