# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: disableautokick
description: Hides a players HUD
homepage: "https://github.com/MoonlyDays"
authors:
  - Moonly Days
inputs:
  - sm_hidehud.sp
version: 1.0.0
