# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: afkmanager4
homepage: "http://www.dawgclan.net"
description: A package for managing AFKs in a game.
inputs:
  - afkmanager4.sp
version: 4.3.1
