# yaml-language-server: $schema=https://raw.githubusercontent.com/leighmacdonald/smpkg-repo/refs/heads/master/schema.yaml

name: connect
homepage: https://forums.alliedmods.net/showthread.php?t=162489
