# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: connect
description: A safer OnClientPreConnect forward
homepage: "https://github.com/asherkin/connect"
version: 1.4.0
