$schema: >-
  https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json
name: admin_allspec
homepage: "https://github.com/Drifter321/admin-all-spec"
description: Allow admins to spectate
version: 1.0.2
inputs:
  - admin-allspec.sp
