# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: admin_allspec
homepage: "https://github.com/Drifter321/admin-all-spec"
description: Allow admins to spectate
version: 1.0.2
inputs: ["admin-allspec.sp"]
authors:
  - Dr!fter
