# yaml-language-server: $schema=../plugin.schema.json
---
name: votescramble
description: Vote to scramble teams
homepage: "https://uncletopia.com"
authors:
  - Nanochip
  - viora
  - raspy
inputs:
  - votescramble.sp
version: 1.5.0
dependencies:
  - nativevotes
