$schema: >-
  https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json
name: votescramble
description: Vote to scramble teams
homepage: "https://uncletopia.com"
authors:
  - Nanochip
  - viora
  - raspy
inputs:
  - votescramble.sp
version: 1.5.0
