# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: tf2_comp_fixes
description: Various technical or gameplay changes catered towards competitive play
homepage: "https://github.com/ldesgoui/tf2-comp-fixes"
authors:
  - ldesgoui
inputs:
  - tf2-comp-fixes.sp
version: 1.17.2
