# yaml-language-server: $schema=../plugin.schema.json
---
name: disableautokick
description: Protects players with reserve slot from being autokicked
homepage: "http://www.righttorule.com/"
inputs:
  - disableautokick.sp
version: 0.0.3
