# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: disableautokick
description: Protects players with reserve slot from being autokicked
homepage: "http://www.righttorule.com/"
inputs:
  - disableautokick.sp
version: 0.0.3
