# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: extendedmapconfig
description: Allows you to use seperate config files for each gametype and map.
homepage: "http://sourcemod.corks.nl/"
inputs:
  - extendedmapconfig.sp
version: 1.1.1
