# yaml-language-server: $schema=https://raw.githubusercontent.com/sm-pkg/plugins/refs/heads/master/plugin.schema.json
---
name: waitingdoors
description: Open spawn doors during waiting for players round
homepage: "https://sappho.io/"
authors:
  - stephanie
  - Nanochip
  - Lange
inputs:
  - waitingdoors.sp
version: 0.0.6
