# yaml-language-server: $schema=../plugin.schema.json
---
name: tidychat
description: Cleans up the chat area
homepage: "https://forums.alliedmods.net/showthread.php?t=101340"
authors:
  - linux_lover
inputs:
  - tidychat.sp
version: 0.5.0
